version: '3.8'

services:
  postgres:
    image: postgres:15.0
    container_name: weather-db-container
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    container_name: weather-redis-container
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  weather-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  cache:
    driver: local
  db_data: